### ISSUE TITLE
Will this continue to be updated?

### ISSUE THREAD

**Issue by BaiGave** [Sam54123/mc-world-export#11]
Will this continue to be updated?

**Comment by Sam54123** [comment]
It is still in active development, and I don't have any intentions of ceasing development any time soon! Is there anything in particular you're curious about?

**Comment by BaiGave** [comment]
I don't see the water in blender, and there is a problem with placing blocks at the same time, the blocks placed by the player will not be displayed in blender

**Comment by BaiGave** [comment]
And whether the option of removing caves will be added in the future. When I export a large-scale map to blender, there will be billions of vertices, most of which are caves, not the surface. If you can remove these unnecessary vertices, the performance will be much better

**Comment by BaiGave** [comment]
These are the problems I encountered in use, if possible, I hope they can be resolved.

**Comment by Sam54123** [comment]
> I don't see the water in blender

Water and other fluids are not currently supported, but they're being actively worked on! Check the `fluids` branch.

> and there is a problem with placing blocks at the same time, the blocks placed by the player will not be displayed in blender

That's a known issue, and it's been fixed! Download the latest release to get the fix.

> And whether the option of removing caves will be added in the future.

I've had a few people ask about that. From a technical perspective, cave vertices don't impact performance all that much, but I might add it given that it's a highly-requested feature. For now, you can raise the lower depth while exporting to remove the caves from the exported file.

Hope this helps!
