### ISSUE TITLE
Replace first-person camera movements

### ISSUE THREAD

**Issue by couleurm** [Sam54123/mc-world-export#12]
Hello Sam,

I've recently discovered your addon for ReplayMod after taking another look at an [issue](https://github.com/ReplayMod/ReplayMod/issues/738) I've made on ReplayMod's.

Does your addon or Blender give the option to replace a player's <ins>first person POV head movement</ins> to something manually recorded/more accurate? You're probably aware of it's choppiness and I'd like having a way (__any way__) to make it useable (I still need to figure out how to capture and synchronize that)

Could/is it supported in your addon/blender and if yes which kind of format does it require/support?

Thank you for your contribution to the community

**Comment by Sam54123** [comment]
While there isn't any native support for something like that, you _could_ screen record your game and then 3D track the camera, aligning the tracked camera with the imported scene!

**Comment by couleurm** [comment]
Ahh 3d tracking may be it, it seems imaginable to replace with a blender export as well! Will look in making Minecraft more suitable to "3d" tracking with something like texture packs that have all blocks be trackers :-)

Thanks! 

If other lurkers reading this knowledgeable in video tracking let me know 😋!

**Comment by Sam54123** [comment]
I'm not very good at camera tracking myself, but I know enough to say you don't need to go as far as making a texture pack. The vanilla textures should be trackable enough.

Here's a good resource if you're looking to learn! https://youtu.be/InIuTtt7W3E
