### ISSUE TITLE
Replays do not export properly if FFmpeg is not installed

### ISSUE THREAD

**Issue by Sam54123** [Sam54123/mc-world-export#16]
The replay export system doesn't actually use FFmpeg, so this *shouldn't* be a problem, but the Replay Mod somehow screws things up if it detects FFmpeg is not installed.

**Comment by Sam54123** [comment]
Originally reported by [Superkat3](https://github.com/Superkat32) in #14.

**Comment by JaaiDead** [comment]
i see i think this mod has good potenital

**Comment by JaaiDead** [comment]
ez fix just make a huge propmt  and have a minecraft mod say this requirez ffmpeg and replay mod lol

**Comment by Sam54123** [comment]
> ez fix just make a huge propmt and have a minecraft mod say this requirez ffmpeg and replay mod lol

That's a band-aid fix. People with the Replay Mod generally already have ffmpeg because RM requires it, so this isn't a huge issue, but the exporter shouldn't depend on something that it doesn't need.

**Comment by Sam54123** [comment]
Fixed in v0.7.0
