### ISSUE TITLE
When will the block breaking animation be launched?

### ISSUE THREAD

**Issue by BaiGave** [Sam54123/mc-world-export#18]
I very much hope that the destruction of the block can be recorded. Not only this, I also hope that the operation of the player switching the item in hand can also be recorded, as well as the behavior of the player eating, and its particle effects.

**Comment by BaiGave** [comment]
It is very simple to implement block destruction animation in blender, you can refer to this tutorial https://www.youtube.com/watch?v=xlD84cpTSBo
But it's kind of time consuming, if I want to mine very, very many blocks
So is there any way to solve it？

**Comment by BaiGave** [comment]
The animation of eating is not displayed normally on my side, probably because of the installation of this mod
https://www.curseforge.com/minecraft/mc-mods/not-enough-animations

**Comment by Sam54123** [comment]
In the future there may be a way to automatically import block breaking, but it's much harder to do programmatically and in a way that's compatible with the rest of the mod than is shown in that video. 

For now, I would focus on crafting your shot, and implement block breaking manually for when you can actually see it. 

Or if you *really* need breaking animations for all your blocks, you can re-import your camera animations into Minecraft using the `camera-paths` branch.
