### ISSUE TITLE
Many blocks, such as Fire, Soul Fire and Portals will fail to import in blender.

### ISSUE THREAD

**Issue by EmqsaGit** [Sam54123/mc-world-export#36]
I've been trying to load these blocks in blender and it will just fail with an error message related to missing assets to those blocks.

**Comment by Sam54123** [comment]
That's weird. Can you send the error message and the offending replay file?

**Comment by Sam54123** [comment]
@EmqsaGit Any updates? I'm gonna close this issue if not.
