### ISSUE TITLE
Mod breaks on 1.19.3 trying to use an inexistent math class removed in 1.19.3, and blames it on other mods

### ISSUE THREAD

**Issue by EmqsaGit** [Sam54123/mc-world-export#37]
I was trying to use this mod to make animations with PFM blocks on 1.19.3 and the mod kept blaming PFM trying to mixin the rendering but the error says mc-world-export tries to use an old math class. That only happens with mods that add blocks, tested with Paladin's Furniture Mod and Macaw's Roofs.

**Comment by Sam54123** [comment]
1.19.3 is not supported yet (see #35). Due to the massive demand, I aim to support it in the next update.
