### ISSUE TITLE
Placing Blocks

### ISSUE THREAD

**Issue by ClockTheSenior** [Sam54123/mc-world-export#47]
Blocks that were placed in the exported replay do not show. This is likely a model adapter bug. Here is a some footage:

![blender_A9vghJNncR](https://user-images.githubusercontent.com/106481085/224491727-4a32bf92-20c5-4ffb-b76e-1d3766550330.gif)

**Comment by Sam54123** [comment]
This is a known issue. Closing and re-opening the file should fix it. See #21
