### ISSUE TITLE
Hotbar Block Swapping

### ISSUE THREAD

**Issue by ClockTheSenior** [Sam54123/mc-world-export#50]
When swapping Blocks in the hand the Block (in the hand) is invisible.

**Comment by Sam54123** [comment]
Can you send the offending `replay` and `mcpr` files?

**Comment by ClockTheSenior** [comment]
[gimmeurdiscord.zip](https://github.com/Sam54123/mc-world-export/files/10951844/gimmeurdiscord.zip)
