### ISSUE TITLE
Limit Entity Exporting

### ISSUE THREAD

**Issue by ClockTheSenior** [Sam54123/mc-world-export#51]
This is a bug which can highly optimize the scene! The Issue is that the mod still exports the entities regardless of what area was chosen to be exported.

![image](https://user-images.githubusercontent.com/106481085/224569946-e2af8535-2536-4130-9f46-2eb41c6c1192.png)

As you can see, the blocks cut off above because that was the area that I chose. But the entities do not. Good luck fixing that!

**Comment by Sam54123** [comment]
This is a known issue and I'm working on a fix.

**Comment by Sam54123** [comment]
Fixed in the new branch. Will be merged alongside the UI overhaul.
