### ISSUE TITLE
Mod can't export when Shulkers are in the replay

### ISSUE THREAD

**Issue by jemplix** [Sam54123/mc-world-export#54]
When trying to export a replay shot, it kept crashing. After extensive testing, I've come to the conclusion it's a Shulker doing it. Not sure why exactly, but here's the crash report
[crash-2023-03-27_02.55.00-client.txt](https://github.com/Sam54123/mc-world-export/files/11075618/crash-2023-03-27_02.55.00-client.txt)

**Comment by Sam54123** [comment]
Thanks for reporting! I've figured out what caused the issue, and it seems to be an issue with a recent Minecraft update. I'll get working on a fix.

**Comment by Sam54123** [comment]
Fixed in 517eb81742426135a2dc04f68fd9588e0e3579b3

**Comment by jemplix** [comment]
You're the best!
