### ISSUE TITLE
I need some help!

### ISSUE THREAD

**Issue by BaiGave** [Sam54123/mc-world-export#60]
I'm writing a blender plugin for importing and exporting mc maps（with mod blocks, such as byg, little blocks,yuushya.....）。But I'm having some problems
    Now the .schem file can be imported normally, but I realized that if I want to import and export the map archive, I need to read, create and write to the .mca file
    I checked the information on the Internet for a long time, but all I can know is that the .mca file has an 8k area storage block file location length and change time, and then the nbt file after zlib compression. I don't understand how to do this in python, if you can help me, I would appreciate it

**Comment by BaiGave** [comment]
![20230516193902](https://github.com/Sam54123/mc-world-export/assets/107305554/96ea333c-ac97-4243-9e58-887ae8754e5d)

**Comment by BaiGave** [comment]
The above is what my current code does

**Comment by Sam54123** [comment]
Ohhh boyyy, welcome to the rabbit hole. I actually faced this very problem in a project a few years back, and had some help fixing it. Here's my friend's pull request if you wanna look at code: https://github.com/Sam54123/Scaffold/pull/12

**Comment by BaiGave** [comment]
Thank you so much!!!
